export default {
    "_id": "5bb6f5970e0a26338e01fb9a",
    "air_date": "2019-11-12",
    "episodes": [
      {
        "air_date": "2019-11-12",
        "episode_number": 1,
        "id": 1586260,
        "name": "Chapter 1: The Mandalorian",
        "overview": "A Mandalorian bounty hunter tracks a target for a well-paying client.",
        "production_code": "161176",
        "runtime": 41,
        "season_number": 1,
        "show_id": 82856,
        "still_path": "/lr8OEa0GzjZ0qmD9NuuMj6TRWxF.jpg",
        "vote_average": 7.8,
        "vote_count": 154,
        "crew": [
          {
            "job": "Editor",
            "department": "Editing",
            "credit_id": "5cb87a27c3a36872c98161fd",
            "adult": false,
            "gender": 2,
            "id": 1580025,
            "known_for_department": "Editing",
            "name": "Jeff Seibenick",
            "original_name": "Jeff Seibenick",
            "popularity": 0.98,
            "profile_path": null
          },
          {
            "job": "Director of Photography",
            "department": "Camera",
            "credit_id": "5cb879fac3a3686b0b86531f",
            "adult": false,
            "gender": 2,
            "id": 67113,
            "known_for_department": "Camera",
            "name": "Greig Fraser",
            "original_name": "Greig Fraser",
            "popularity": 2.366,
            "profile_path": "/cwj0aValmr7TGQ2OOQk5CAy1PWf.jpg"
          },
          {
            "job": "Writer",
            "department": "Writing",
            "credit_id": "5f4fe593a6fdaa0036948536",
            "adult": false,
            "gender": 2,
            "id": 15277,
            "known_for_department": "Acting",
            "name": "Jon Favreau",
            "original_name": "Jon Favreau",
            "popularity": 25.467,
            "profile_path": "/8MtRRnEHaBSw8Ztdl8saXiw1egP.jpg"
          },
          {
            "job": "First Assistant Director",
            "department": "Directing",
            "credit_id": "5f9e62a5344a8e00349cb56e",
            "adult": false,
            "gender": 1,
            "id": 2838919,
            "known_for_department": "Directing",
            "name": "Kim Richards",
            "original_name": "Kim Richards",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Production Supervisor",
            "department": "Production",
            "credit_id": "5fd03b3a0ce1bc003ef02c33",
            "adult": false,
            "gender": 0,
            "id": 2152272,
            "known_for_department": "Production",
            "name": "Clint Spillers",
            "original_name": "Clint Spillers",
            "popularity": 0.999,
            "profile_path": null
          },
          {
            "job": "Additional Director of Photography",
            "department": "Camera",
            "credit_id": "5fd047f5d18fb90040f7d077",
            "adult": false,
            "gender": 2,
            "id": 1406766,
            "known_for_department": "Camera",
            "name": "Barry Idoine",
            "original_name": "Barry Idoine",
            "popularity": 5.796,
            "profile_path": "/k12a8mxmefY54hQTzb2i3xIiuQQ.jpg"
          },
          {
            "job": "Set Decoration",
            "department": "Art",
            "credit_id": "5fd04b9ae9c0dc003c36eb4e",
            "adult": false,
            "gender": 1,
            "id": 1389126,
            "known_for_department": "Art",
            "name": "Amanda Moss Serino",
            "original_name": "Amanda Moss Serino",
            "popularity": 1.4,
            "profile_path": null
          },
          {
            "job": "Property Master",
            "department": "Art",
            "credit_id": "5fd6c5a0db952d003e7cb5b3",
            "adult": false,
            "gender": 0,
            "id": 1463356,
            "known_for_department": "Art",
            "name": "Josh Roth",
            "original_name": "Josh Roth",
            "popularity": 0.716,
            "profile_path": null
          },
          {
            "job": "Art Direction",
            "department": "Art",
            "credit_id": "5fd6c769681888004097d1ca",
            "adult": false,
            "gender": 0,
            "id": 1324829,
            "known_for_department": "Art",
            "name": "Michael Manson",
            "original_name": "Michael Manson",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Director",
            "department": "Directing",
            "credit_id": "600f834e813cb6004280eea3",
            "adult": false,
            "gender": 2,
            "id": 71538,
            "known_for_department": "Production",
            "name": "Dave Filoni",
            "original_name": "Dave Filoni",
            "popularity": 4.359,
            "profile_path": "/dDTTrShpCnCacxB3LhpPffFIdB5.jpg"
          }
        ],
        "guest_stars": [
          {
            "character": "The Client",
            "credit_id": "5de214d54f5801000f00770c",
            "order": 2,
            "adult": false,
            "gender": 2,
            "id": 6818,
            "known_for_department": "Directing",
            "name": "Werner Herzog",
            "original_name": "Werner Herzog",
            "popularity": 4.553,
            "profile_path": "/vokqteY91Pda0L13pTqTzTCo7vV.jpg"
          },
          {
            "character": "Bartender",
            "credit_id": "5dcb3476a06efe0014df6be0",
            "order": 500,
            "adult": false,
            "gender": 2,
            "id": 38571,
            "known_for_department": "Acting",
            "name": "John Beasley",
            "original_name": "John Beasley",
            "popularity": 6.943,
            "profile_path": "/tpZQojv2UfelPHr1eSphcp0iEpJ.jpg"
          },
          {
            "character": "Alpha Trawler",
            "credit_id": "5dcb34aecc277c0014dec9c8",
            "order": 501,
            "adult": false,
            "gender": 2,
            "id": 1105706,
            "known_for_department": "Acting",
            "name": "Tait Fletcher",
            "original_name": "Tait Fletcher",
            "popularity": 37.527,
            "profile_path": "/zAVsHT2GBLPaQ4RpTopnHvIrCbv.jpg"
          },
          {
            "character": "Quarren Trawler",
            "credit_id": "5dcb34ef79a1c30013430eeb",
            "order": 502,
            "adult": false,
            "gender": 2,
            "id": 1686301,
            "known_for_department": "Acting",
            "name": "Dmitrious Bistrevsky",
            "original_name": "Dmitrious Bistrevsky",
            "popularity": 1.556,
            "profile_path": "/lxh4R3KDeg2bdV6WZWQr8maTXh0.jpg"
          },
          {
            "character": "Ferryman",
            "credit_id": "5dcb351779a1c30013430f40",
            "order": 503,
            "adult": false,
            "gender": 2,
            "id": 2456535,
            "known_for_department": "Acting",
            "name": "Chris Bartlett",
            "original_name": "Chris Bartlett",
            "popularity": 2.599,
            "profile_path": "/tSD5t3Iq0lPeMi13EYa9A3nPLNS.jpg"
          },
          {
            "character": "Speeder Pilot",
            "credit_id": "5dcb352fa06efe0017df455e",
            "order": 504,
            "adult": false,
            "gender": 2,
            "id": 20405,
            "known_for_department": "Acting",
            "name": "Brian Posehn",
            "original_name": "Brian Posehn",
            "popularity": 10.467,
            "profile_path": "/kg93LNpDQaRoosR4gVt7SsA3oL1.jpg"
          },
          {
            "character": "Beta Trawler",
            "credit_id": "5dcb36b4cc277c0014dece8e",
            "order": 505,
            "adult": false,
            "gender": 2,
            "id": 2456540,
            "known_for_department": "Crew",
            "name": "Ryan Watson",
            "original_name": "Ryan Watson",
            "popularity": 1.114,
            "profile_path": "/3Ld7rcvDDtkCpnKw5MSprwrbPio.jpg"
          },
          {
            "character": "Bounty Hunter Gekko",
            "credit_id": "5df6f60ba6d9310012dac8eb",
            "order": 529,
            "adult": false,
            "gender": 2,
            "id": 1215981,
            "known_for_department": "Acting",
            "name": "Dominic Pace",
            "original_name": "Dominic Pace",
            "popularity": 4.017,
            "profile_path": "/9req1Q8f8cR1dKCcLBYzNHQ1cx9.jpg"
          },
          {
            "character": "Kuiil (voice)",
            "credit_id": "5df6f4ac65686e00188611d3",
            "order": 539,
            "adult": false,
            "gender": 2,
            "id": 1733,
            "known_for_department": "Acting",
            "name": "Nick Nolte",
            "original_name": "Nick Nolte",
            "popularity": 18.97,
            "profile_path": "/jpYzFBi6zfn8CHVaXmqgiOTas4V.jpg"
          },
          {
            "character": "IG-11 (Performance Artist)",
            "credit_id": "5dcef449e263bb001175bae2",
            "order": 546,
            "adult": false,
            "gender": 2,
            "id": 62787,
            "known_for_department": "Acting",
            "name": "Rio Hackford",
            "original_name": "Rio Hackford",
            "popularity": 5.826,
            "profile_path": "/lzRk0FsLIJU8pNHhAlF5jijcdJr.jpg"
          },
          {
            "character": "IG-11 (voice)",
            "credit_id": "5de214010cd446001235fa6e",
            "order": 547,
            "adult": false,
            "gender": 2,
            "id": 55934,
            "known_for_department": "Directing",
            "name": "Taika Waititi",
            "original_name": "Taika Waititi",
            "popularity": 27.104,
            "profile_path": "/aH6MgwFhomAPNBRPyO2fhpU5kbk.jpg"
          },
          {
            "character": "Armorer",
            "credit_id": "5dcef473e263bb001175bb44",
            "order": 560,
            "adult": false,
            "gender": 1,
            "id": 1256020,
            "known_for_department": "Acting",
            "name": "Emily Swallow",
            "original_name": "Emily Swallow",
            "popularity": 24.183,
            "profile_path": "/jlgPZqdMsQaVv30oMqc40LzHYIw.jpg"
          },
          {
            "character": "Din Djarin Father",
            "credit_id": "5e05fab0eda4b7001228f845",
            "order": 563,
            "adult": false,
            "gender": 2,
            "id": 1567857,
            "known_for_department": "Acting",
            "name": "Bernard Bullen",
            "original_name": "Bernard Bullen",
            "popularity": 1.4,
            "profile_path": "/dmUerfyPtPoLZ7F363ShB7fbavD.jpg"
          },
          {
            "character": "Kuiil (Performance Artist)",
            "credit_id": "5dcef41cb76cbb00137768bb",
            "order": 566,
            "adult": false,
            "gender": 1,
            "id": 95747,
            "known_for_department": "Acting",
            "name": "Misty Rosas",
            "original_name": "Misty Rosas",
            "popularity": 4.301,
            "profile_path": "/aCa0ukemG7x3wAxtR1BM5v0BvrL.jpg"
          },
          {
            "character": "Mythrol",
            "credit_id": "5dcb349079a1c30013430e54",
            "order": 575,
            "adult": false,
            "gender": 2,
            "id": 52117,
            "known_for_department": "Acting",
            "name": "Horatio Sanz",
            "original_name": "Horatio Sanz",
            "popularity": 4.33,
            "profile_path": "/ckz64bpwFOhF1tMu1klDk5AT9Ck.jpg"
          },
          {
            "character": "Din Djarin Mother",
            "credit_id": "5df6f5e9a6d9310017dace60",
            "order": 602,
            "adult": false,
            "gender": 1,
            "id": 2477245,
            "known_for_department": "Acting",
            "name": "Alexandra Manea",
            "original_name": "Alexandra Manea",
            "popularity": 3.436,
            "profile_path": "/zQm8nQtS7E8eZeQLeDQNjObPQEL.jpg"
          },
          {
            "character": "Greef Karga",
            "credit_id": "5fe96fe4c9054f003d3bfaea",
            "order": 605,
            "adult": false,
            "gender": 2,
            "id": 1101,
            "known_for_department": "Acting",
            "name": "Carl Weathers",
            "original_name": "Carl Weathers",
            "popularity": 31.528,
            "profile_path": "/9Tot1ywxTQA3vFCcAjyK6h9Dao3.jpg"
          },
          {
            "character": "Young Mandalorian (uncredited)",
            "credit_id": "60ec9f6bc2b9df00290ad2a0",
            "order": 612,
            "adult": false,
            "gender": 2,
            "id": 2491651,
            "known_for_department": "Acting",
            "name": "Aidan Bertola",
            "original_name": "Aidan Bertola",
            "popularity": 1.532,
            "profile_path": "/xMXATWE4X3geHyVCE3vqTB6KcPz.jpg"
          },
          {
            "character": "Dr. Penn Pershing",
            "credit_id": "64118697323eba00c5ec3c90",
            "order": 624,
            "adult": false,
            "gender": 2,
            "id": 167862,
            "known_for_department": "Acting",
            "name": "Omid Abtahi",
            "original_name": "Omid Abtahi",
            "popularity": 6.347,
            "profile_path": "/gyXa16wW4vSUFmH014JGojstDeN.jpg"
          }
        ]
      },
      {
        "air_date": "2019-11-15",
        "episode_number": 2,
        "id": 1857024,
        "name": "Chapter 2: The Child",
        "overview": "Target in-hand, the Mandalorian must now contend with scavengers.",
        "production_code": "",
        "runtime": 34,
        "season_number": 1,
        "show_id": 82856,
        "still_path": "/b8y9qAq2ZdU27Ua1lJxyNQbmzQE.jpg",
        "vote_average": 7.9,
        "vote_count": 125,
        "crew": [
          {
            "job": "Director of Photography",
            "department": "Camera",
            "credit_id": "5cb87a0c0e0a266b90f14452",
            "adult": false,
            "gender": 2,
            "id": 1406766,
            "known_for_department": "Camera",
            "name": "Barry Idoine",
            "original_name": "Barry Idoine",
            "popularity": 5.796,
            "profile_path": "/k12a8mxmefY54hQTzb2i3xIiuQQ.jpg"
          },
          {
            "job": "Editor",
            "department": "Editing",
            "credit_id": "5dd6b9503faba00015f70a1d",
            "adult": false,
            "gender": 2,
            "id": 71279,
            "known_for_department": "Editing",
            "name": "Andrew S. Eisen",
            "original_name": "Andrew S. Eisen",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Writer",
            "department": "Writing",
            "credit_id": "5f4fe593a6fdaa0036948536",
            "adult": false,
            "gender": 2,
            "id": 15277,
            "known_for_department": "Acting",
            "name": "Jon Favreau",
            "original_name": "Jon Favreau",
            "popularity": 25.467,
            "profile_path": "/8MtRRnEHaBSw8Ztdl8saXiw1egP.jpg"
          },
          {
            "job": "Unit Production Manager",
            "department": "Production",
            "credit_id": "5fa0655e160e730037452fa9",
            "adult": false,
            "gender": 2,
            "id": 490,
            "known_for_department": "Production",
            "name": "Colin Wilson",
            "original_name": "Colin Wilson",
            "popularity": 3.689,
            "profile_path": "/jsrgEcnuuBZ9ZuB3Qe23ezy9szP.jpg"
          },
          {
            "job": "Second Assistant Director",
            "department": "Directing",
            "credit_id": "5fa0656e7614210036f4bea3",
            "adult": false,
            "gender": 1,
            "id": 2636771,
            "known_for_department": "Directing",
            "name": "Heather Wagner-Wang",
            "original_name": "Heather Wagner-Wang",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "First Assistant Director",
            "department": "Directing",
            "credit_id": "5f9e62a5344a8e00349cb56e",
            "adult": false,
            "gender": 1,
            "id": 2838919,
            "known_for_department": "Directing",
            "name": "Kim Richards",
            "original_name": "Kim Richards",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Visual Effects Supervisor",
            "department": "Visual Effects",
            "credit_id": "5fd037fbc7a7e00042023997",
            "adult": false,
            "gender": 0,
            "id": 1367818,
            "known_for_department": "Visual Effects",
            "name": "Richard Bluff",
            "original_name": "Richard Bluff",
            "popularity": 0.695,
            "profile_path": null
          },
          {
            "job": "Production Supervisor",
            "department": "Production",
            "credit_id": "5fd03b3a0ce1bc003ef02c33",
            "adult": false,
            "gender": 0,
            "id": 2152272,
            "known_for_department": "Production",
            "name": "Clint Spillers",
            "original_name": "Clint Spillers",
            "popularity": 0.999,
            "profile_path": null
          },
          {
            "job": "Additional Director of Photography",
            "department": "Camera",
            "credit_id": "5fd04a1ad7cd06003d7cb4cd",
            "adult": false,
            "gender": 0,
            "id": 2887235,
            "known_for_department": "Camera",
            "name": "Ryley Brown",
            "original_name": "Ryley Brown",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Set Decoration",
            "department": "Art",
            "credit_id": "5fd04b9ae9c0dc003c36eb4e",
            "adult": false,
            "gender": 1,
            "id": 1389126,
            "known_for_department": "Art",
            "name": "Amanda Moss Serino",
            "original_name": "Amanda Moss Serino",
            "popularity": 1.4,
            "profile_path": null
          },
          {
            "job": "Property Master",
            "department": "Art",
            "credit_id": "5fd6c5a0db952d003e7cb5b3",
            "adult": false,
            "gender": 0,
            "id": 1463356,
            "known_for_department": "Art",
            "name": "Josh Roth",
            "original_name": "Josh Roth",
            "popularity": 0.716,
            "profile_path": null
          },
          {
            "job": "Director",
            "department": "Directing",
            "credit_id": "600f832cc433ea003f471ae4",
            "adult": false,
            "gender": 2,
            "id": 51866,
            "known_for_department": "Directing",
            "name": "Rick Famuyiwa",
            "original_name": "Rick Famuyiwa",
            "popularity": 2.597,
            "profile_path": "/zvpQOPiD5RLfjKBJyNgHYNocy7X.jpg"
          }
        ],
        "guest_stars": [
          {
            "character": "Jawa (uncredited)",
            "credit_id": "5de215ea0cd44600143589ac",
            "order": 1,
            "adult": false,
            "gender": 2,
            "id": 2471240,
            "known_for_department": "Acting",
            "name": "Kyle Pacek",
            "original_name": "Kyle Pacek",
            "popularity": 1.22,
            "profile_path": "/6KnQ0GiQgaoyAe4DDkyokwpDoa7.jpg"
          },
          {
            "character": "Jawa Elder",
            "credit_id": "5dd01f062866fa0018875553",
            "order": 506,
            "adult": false,
            "gender": 2,
            "id": 2459450,
            "known_for_department": "Acting",
            "name": "Stephen Jackson Powers Jr.",
            "original_name": "Stephen Jackson Powers Jr.",
            "popularity": 0.695,
            "profile_path": null
          },
          {
            "character": "Jawa (uncredited)",
            "credit_id": "5df6f667d1a89300147b01e0",
            "order": 523,
            "adult": false,
            "gender": 2,
            "id": 1695655,
            "known_for_department": "Acting",
            "name": "Douglas Farrell",
            "original_name": "Douglas Farrell",
            "popularity": 1.614,
            "profile_path": "/zSFkysHQS7Gc2DfSb0K62vZqg3z.jpg"
          },
          {
            "character": "Jawa (uncredited)",
            "credit_id": "5df6f673d1a89300127aaeae",
            "order": 524,
            "adult": false,
            "gender": 2,
            "id": 1324275,
            "known_for_department": "Acting",
            "name": "Joseph S. Griffo",
            "original_name": "Joseph S. Griffo",
            "popularity": 2.183,
            "profile_path": "/ftQygyjVyzgDYbgj19b1TFfAuNG.jpg"
          },
          {
            "character": "Jawa (uncredited)",
            "credit_id": "5df6f69426dac100145389e9",
            "order": 525,
            "adult": false,
            "gender": 1,
            "id": 1869246,
            "known_for_department": "Acting",
            "name": "Molly Miller",
            "original_name": "Molly Miller",
            "popularity": 1.4,
            "profile_path": "/a8I2F1t9bkWVmoAsq9DPr4i9UkJ.jpg"
          },
          {
            "character": "Kuiil (voice)",
            "credit_id": "5df6f4ac65686e00188611d3",
            "order": 539,
            "adult": false,
            "gender": 2,
            "id": 1733,
            "known_for_department": "Acting",
            "name": "Nick Nolte",
            "original_name": "Nick Nolte",
            "popularity": 18.97,
            "profile_path": "/jpYzFBi6zfn8CHVaXmqgiOTas4V.jpg"
          },
          {
            "character": "Kuiil (Performance Artist)",
            "credit_id": "5dcef41cb76cbb00137768bb",
            "order": 566,
            "adult": false,
            "gender": 1,
            "id": 95747,
            "known_for_department": "Acting",
            "name": "Misty Rosas",
            "original_name": "Misty Rosas",
            "popularity": 4.301,
            "profile_path": "/aCa0ukemG7x3wAxtR1BM5v0BvrL.jpg"
          }
        ]
      },
      {
        "air_date": "2019-11-22",
        "episode_number": 3,
        "id": 1980403,
        "name": "Chapter 3: The Sin",
        "overview": "The battered Mandalorian returns to his client for reward.",
        "production_code": "",
        "runtime": 39,
        "season_number": 1,
        "show_id": 82856,
        "still_path": "/5wGkymV2D9P9ZGI2wP0PefIwFol.jpg",
        "vote_average": 8.5,
        "vote_count": 116,
        "crew": [
          {
            "job": "Editor",
            "department": "Editing",
            "credit_id": "5cb87a27c3a36872c98161fd",
            "adult": false,
            "gender": 2,
            "id": 1580025,
            "known_for_department": "Editing",
            "name": "Jeff Seibenick",
            "original_name": "Jeff Seibenick",
            "popularity": 0.98,
            "profile_path": null
          },
          {
            "job": "Director of Photography",
            "department": "Camera",
            "credit_id": "5cb879fac3a3686b0b86531f",
            "adult": false,
            "gender": 2,
            "id": 67113,
            "known_for_department": "Camera",
            "name": "Greig Fraser",
            "original_name": "Greig Fraser",
            "popularity": 2.366,
            "profile_path": "/cwj0aValmr7TGQ2OOQk5CAy1PWf.jpg"
          },
          {
            "job": "Writer",
            "department": "Writing",
            "credit_id": "5f4fe593a6fdaa0036948536",
            "adult": false,
            "gender": 2,
            "id": 15277,
            "known_for_department": "Acting",
            "name": "Jon Favreau",
            "original_name": "Jon Favreau",
            "popularity": 25.467,
            "profile_path": "/8MtRRnEHaBSw8Ztdl8saXiw1egP.jpg"
          },
          {
            "job": "First Assistant Director",
            "department": "Directing",
            "credit_id": "5f9e62a5344a8e00349cb56e",
            "adult": false,
            "gender": 1,
            "id": 2838919,
            "known_for_department": "Directing",
            "name": "Kim Richards",
            "original_name": "Kim Richards",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Production Supervisor",
            "department": "Production",
            "credit_id": "5fd03b3a0ce1bc003ef02c33",
            "adult": false,
            "gender": 0,
            "id": 2152272,
            "known_for_department": "Production",
            "name": "Clint Spillers",
            "original_name": "Clint Spillers",
            "popularity": 0.999,
            "profile_path": null
          },
          {
            "job": "Additional Director of Photography",
            "department": "Camera",
            "credit_id": "5fd047f5d18fb90040f7d077",
            "adult": false,
            "gender": 2,
            "id": 1406766,
            "known_for_department": "Camera",
            "name": "Barry Idoine",
            "original_name": "Barry Idoine",
            "popularity": 5.796,
            "profile_path": "/k12a8mxmefY54hQTzb2i3xIiuQQ.jpg"
          },
          {
            "job": "Set Decoration",
            "department": "Art",
            "credit_id": "5fd04b9ae9c0dc003c36eb4e",
            "adult": false,
            "gender": 1,
            "id": 1389126,
            "known_for_department": "Art",
            "name": "Amanda Moss Serino",
            "original_name": "Amanda Moss Serino",
            "popularity": 1.4,
            "profile_path": null
          },
          {
            "job": "Property Master",
            "department": "Art",
            "credit_id": "5fd6c5a0db952d003e7cb5b3",
            "adult": false,
            "gender": 0,
            "id": 1463356,
            "known_for_department": "Art",
            "name": "Josh Roth",
            "original_name": "Josh Roth",
            "popularity": 0.716,
            "profile_path": null
          },
          {
            "job": "Art Direction",
            "department": "Art",
            "credit_id": "5fd6c769681888004097d1ca",
            "adult": false,
            "gender": 0,
            "id": 1324829,
            "known_for_department": "Art",
            "name": "Michael Manson",
            "original_name": "Michael Manson",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Director",
            "department": "Directing",
            "credit_id": "600f83920816c700417d2dc5",
            "adult": false,
            "gender": 1,
            "id": 928830,
            "known_for_department": "Directing",
            "name": "Deborah Chow",
            "original_name": "Deborah Chow",
            "popularity": 6.92,
            "profile_path": "/7XiXU4d7JqPGbhiGCvaRQclISRT.jpg"
          }
        ],
        "guest_stars": [
          {
            "character": "Jawa (uncredited)",
            "credit_id": "5de215ea0cd44600143589ac",
            "order": 1,
            "adult": false,
            "gender": 2,
            "id": 2471240,
            "known_for_department": "Acting",
            "name": "Kyle Pacek",
            "original_name": "Kyle Pacek",
            "popularity": 1.22,
            "profile_path": "/6KnQ0GiQgaoyAe4DDkyokwpDoa7.jpg"
          },
          {
            "character": "The Client",
            "credit_id": "5de214d54f5801000f00770c",
            "order": 2,
            "adult": false,
            "gender": 2,
            "id": 6818,
            "known_for_department": "Directing",
            "name": "Werner Herzog",
            "original_name": "Werner Herzog",
            "popularity": 4.553,
            "profile_path": "/vokqteY91Pda0L13pTqTzTCo7vV.jpg"
          },
          {
            "character": "Paz Vizsla",
            "credit_id": "5de2151c4f580100120089df",
            "order": 515,
            "adult": false,
            "gender": 2,
            "id": 1105706,
            "known_for_department": "Acting",
            "name": "Tait Fletcher",
            "original_name": "Tait Fletcher",
            "popularity": 37.527,
            "profile_path": "/zAVsHT2GBLPaQ4RpTopnHvIrCbv.jpg"
          },
          {
            "character": "Bounty Hunter",
            "credit_id": "5df6f6d465686e00138677fe",
            "order": 526,
            "adult": false,
            "gender": 2,
            "id": 2419200,
            "known_for_department": "Acting",
            "name": "Jacob Glenn Aquino",
            "original_name": "Jacob Glenn Aquino",
            "popularity": 0.6,
            "profile_path": "/x3kpzicLElN7FaewxREph6W2Om5.jpg"
          },
          {
            "character": "Paz Vizsla (voice)",
            "credit_id": "5df6f6ec65686e0015864a33",
            "order": 527,
            "adult": false,
            "gender": 2,
            "id": 15277,
            "known_for_department": "Acting",
            "name": "Jon Favreau",
            "original_name": "Jon Favreau",
            "popularity": 25.467,
            "profile_path": "/8MtRRnEHaBSw8Ztdl8saXiw1egP.jpg"
          },
          {
            "character": "House Patron",
            "credit_id": "5de215560cd4460019360a8f",
            "order": 528,
            "adult": false,
            "gender": 2,
            "id": 2471239,
            "known_for_department": "Acting",
            "name": "Luis Richard Gomez",
            "original_name": "Luis Richard Gomez",
            "popularity": 1.62,
            "profile_path": "/2UmeS1kcCs157ihXoJc72vVWTz.jpg"
          },
          {
            "character": "Bounty Hunter Gekko",
            "credit_id": "5df6f60ba6d9310012dac8eb",
            "order": 529,
            "adult": false,
            "gender": 2,
            "id": 1215981,
            "known_for_department": "Acting",
            "name": "Dominic Pace",
            "original_name": "Dominic Pace",
            "popularity": 4.017,
            "profile_path": "/9req1Q8f8cR1dKCcLBYzNHQ1cx9.jpg"
          },
          {
            "character": "Human Bounty Hunter",
            "credit_id": "5df6f733d1a89300127ab072",
            "order": 530,
            "adult": false,
            "gender": 2,
            "id": 1047704,
            "known_for_department": "Production",
            "name": "Jude S. Walko",
            "original_name": "Jude S. Walko",
            "popularity": 1.4,
            "profile_path": "/2G2bQRPEWDnRS7jfvzwztYtcwE8.jpg"
          },
          {
            "character": "Armorer",
            "credit_id": "5dcef473e263bb001175bb44",
            "order": 560,
            "adult": false,
            "gender": 1,
            "id": 1256020,
            "known_for_department": "Acting",
            "name": "Emily Swallow",
            "original_name": "Emily Swallow",
            "popularity": 24.183,
            "profile_path": "/jlgPZqdMsQaVv30oMqc40LzHYIw.jpg"
          },
          {
            "character": "Din Djarin Father",
            "credit_id": "5e05fab0eda4b7001228f845",
            "order": 563,
            "adult": false,
            "gender": 2,
            "id": 1567857,
            "known_for_department": "Acting",
            "name": "Bernard Bullen",
            "original_name": "Bernard Bullen",
            "popularity": 1.4,
            "profile_path": "/dmUerfyPtPoLZ7F363ShB7fbavD.jpg"
          },
          {
            "character": "Din Djarin Mother",
            "credit_id": "5df6f5e9a6d9310017dace60",
            "order": 602,
            "adult": false,
            "gender": 1,
            "id": 2477245,
            "known_for_department": "Acting",
            "name": "Alexandra Manea",
            "original_name": "Alexandra Manea",
            "popularity": 3.436,
            "profile_path": "/zQm8nQtS7E8eZeQLeDQNjObPQEL.jpg"
          },
          {
            "character": "Greef Karga",
            "credit_id": "5fe96fe4c9054f003d3bfaea",
            "order": 605,
            "adult": false,
            "gender": 2,
            "id": 1101,
            "known_for_department": "Acting",
            "name": "Carl Weathers",
            "original_name": "Carl Weathers",
            "popularity": 31.528,
            "profile_path": "/9Tot1ywxTQA3vFCcAjyK6h9Dao3.jpg"
          },
          {
            "character": "Young Mandalorian (uncredited)",
            "credit_id": "60ec9f6bc2b9df00290ad2a0",
            "order": 612,
            "adult": false,
            "gender": 2,
            "id": 2491651,
            "known_for_department": "Acting",
            "name": "Aidan Bertola",
            "original_name": "Aidan Bertola",
            "popularity": 1.532,
            "profile_path": "/xMXATWE4X3geHyVCE3vqTB6KcPz.jpg"
          },
          {
            "character": "Dr. Penn Pershing",
            "credit_id": "64118697323eba00c5ec3c90",
            "order": 624,
            "adult": false,
            "gender": 2,
            "id": 167862,
            "known_for_department": "Acting",
            "name": "Omid Abtahi",
            "original_name": "Omid Abtahi",
            "popularity": 6.347,
            "profile_path": "/gyXa16wW4vSUFmH014JGojstDeN.jpg"
          }
        ]
      },
      {
        "air_date": "2019-11-29",
        "episode_number": 4,
        "id": 1980404,
        "name": "Chapter 4: Sanctuary",
        "overview": "The Mandalorian teams up with an ex-soldier to protect a village from raiders.",
        "production_code": "",
        "runtime": 43,
        "season_number": 1,
        "show_id": 82856,
        "still_path": "/cKyE2gtQT5zIpLQHnD3mFNWrKud.jpg",
        "vote_average": 7.7,
        "vote_count": 112,
        "crew": [
          {
            "job": "Director of Photography",
            "department": "Camera",
            "credit_id": "5cb87a0c0e0a266b90f14452",
            "adult": false,
            "gender": 2,
            "id": 1406766,
            "known_for_department": "Camera",
            "name": "Barry Idoine",
            "original_name": "Barry Idoine",
            "popularity": 5.796,
            "profile_path": "/k12a8mxmefY54hQTzb2i3xIiuQQ.jpg"
          },
          {
            "job": "Editor",
            "department": "Editing",
            "credit_id": "5de1e21e0cd446001935c8c4",
            "adult": false,
            "gender": 1,
            "id": 52450,
            "known_for_department": "Editing",
            "name": "Dana E. Glauberman",
            "original_name": "Dana E. Glauberman",
            "popularity": 1.22,
            "profile_path": "/dlik9ug8g80f2PWacp2Qdu3gyfD.jpg"
          },
          {
            "job": "Writer",
            "department": "Writing",
            "credit_id": "5f4fe593a6fdaa0036948536",
            "adult": false,
            "gender": 2,
            "id": 15277,
            "known_for_department": "Acting",
            "name": "Jon Favreau",
            "original_name": "Jon Favreau",
            "popularity": 25.467,
            "profile_path": "/8MtRRnEHaBSw8Ztdl8saXiw1egP.jpg"
          },
          {
            "job": "Production Supervisor",
            "department": "Production",
            "credit_id": "5fd03b3a0ce1bc003ef02c33",
            "adult": false,
            "gender": 0,
            "id": 2152272,
            "known_for_department": "Production",
            "name": "Clint Spillers",
            "original_name": "Clint Spillers",
            "popularity": 0.999,
            "profile_path": null
          },
          {
            "job": "Additional Director of Photography",
            "department": "Camera",
            "credit_id": "5fd04a1ad7cd06003d7cb4cd",
            "adult": false,
            "gender": 0,
            "id": 2887235,
            "known_for_department": "Camera",
            "name": "Ryley Brown",
            "original_name": "Ryley Brown",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Set Decoration",
            "department": "Art",
            "credit_id": "5fd04b9ae9c0dc003c36eb4e",
            "adult": false,
            "gender": 1,
            "id": 1389126,
            "known_for_department": "Art",
            "name": "Amanda Moss Serino",
            "original_name": "Amanda Moss Serino",
            "popularity": 1.4,
            "profile_path": null
          },
          {
            "job": "Stunt Double",
            "department": "Crew",
            "credit_id": "5fd5120d5ed9620040e079d2",
            "adult": false,
            "gender": 2,
            "id": 2889435,
            "known_for_department": "Crew",
            "name": "Barry Lowin",
            "original_name": "Barry Lowin",
            "popularity": 2.549,
            "profile_path": "/o9mP6E3QKpEZgcidyH4ucT5jnmB.jpg"
          },
          {
            "job": "Property Master",
            "department": "Art",
            "credit_id": "5fd6c5a0db952d003e7cb5b3",
            "adult": false,
            "gender": 0,
            "id": 1463356,
            "known_for_department": "Art",
            "name": "Josh Roth",
            "original_name": "Josh Roth",
            "popularity": 0.716,
            "profile_path": null
          },
          {
            "job": "Director",
            "department": "Directing",
            "credit_id": "600f836aed28b9003ffd11e0",
            "adult": false,
            "gender": 1,
            "id": 18997,
            "known_for_department": "Acting",
            "name": "Bryce Dallas Howard",
            "original_name": "Bryce Dallas Howard",
            "popularity": 24.723,
            "profile_path": "/qQX1rhQaJ1G8eMG2RknFKiXfNRc.jpg"
          },
          {
            "job": "Modeling",
            "department": "Visual Effects",
            "credit_id": "607701482faf4d002aae7b56",
            "adult": false,
            "gender": 0,
            "id": 3052019,
            "known_for_department": "Art",
            "name": "Lauren Melody Shell",
            "original_name": "Lauren Melody Shell",
            "popularity": 1.932,
            "profile_path": null
          },
          {
            "job": "Stunt Double",
            "department": "Crew",
            "credit_id": "615f70ae8e2ba6008bf03a2a",
            "adult": false,
            "gender": 1,
            "id": 96754,
            "known_for_department": "Crew",
            "name": "Lauren Mary Kim",
            "original_name": "Lauren Mary Kim",
            "popularity": 2.639,
            "profile_path": "/h3HyClGURD5QsNSWSFhDiLnx8pq.jpg"
          }
        ],
        "guest_stars": [
          {
            "character": "Omera",
            "credit_id": "5de1e2cbc51acd0015f67769",
            "order": 507,
            "adult": false,
            "gender": 1,
            "id": 87310,
            "known_for_department": "Acting",
            "name": "Julia Jones",
            "original_name": "Julia Jones",
            "popularity": 13.743,
            "profile_path": "/9xiA9EGxvIpcCYAlhWHn9LC7fT3.jpg"
          },
          {
            "character": "Winta",
            "credit_id": "5de1e2eb3faba0001909c057",
            "order": 508,
            "adult": false,
            "gender": 1,
            "id": 2471178,
            "known_for_department": "Acting",
            "name": "Isla Farris",
            "original_name": "Isla Farris",
            "popularity": 0.7,
            "profile_path": "/tIkRGDwQOEbIsxSfse8Mixm8XsU.jpg"
          },
          {
            "character": "Stoke",
            "credit_id": "5de1e354a894d600131d1b71",
            "order": 509,
            "adult": false,
            "gender": 2,
            "id": 1370567,
            "known_for_department": "Acting",
            "name": "Eugene Cordero",
            "original_name": "Eugene Cordero",
            "popularity": 6.172,
            "profile_path": "/waruLSR8lXBjhAFL0J6ihuVY62d.jpg"
          },
          {
            "character": "Sorgan Farmer #4",
            "credit_id": "5de1e3cba894d600131d1ced",
            "order": 510,
            "adult": false,
            "gender": 1,
            "id": 2017052,
            "known_for_department": "Production",
            "name": "Aydrea Walden",
            "original_name": "Aydrea Walden",
            "popularity": 1.473,
            "profile_path": "/kOVApwJxys8bCZUshVOCew8lFLV.jpg"
          },
          {
            "character": "Sorgan Farmer #3",
            "credit_id": "5de1e4204f58010012004b74",
            "order": 511,
            "adult": false,
            "gender": 1,
            "id": 2471187,
            "known_for_department": "Acting",
            "name": "Tiffany Thomas",
            "original_name": "Tiffany Thomas",
            "popularity": 0.758,
            "profile_path": "/nTxQr6YeYhAsfonLdiG0dpAd9Do.jpg"
          },
          {
            "character": "Sorgan Farmer #5",
            "credit_id": "5de1e44f3faba000150a73cd",
            "order": 512,
            "adult": false,
            "gender": 1,
            "id": 60390,
            "known_for_department": "Acting",
            "name": "Trula M. Marcus",
            "original_name": "Trula M. Marcus",
            "popularity": 21.818,
            "profile_path": null
          },
          {
            "character": "Klatoonian Raider Captain",
            "credit_id": "5de1e4f8a894d600131d20e2",
            "order": 513,
            "adult": false,
            "gender": 2,
            "id": 1366,
            "known_for_department": "Acting",
            "name": "Sala Baker",
            "original_name": "Sala Baker",
            "popularity": 6.468,
            "profile_path": "/zSWNRVboxLJ3bhj7YBIS76HPCrC.jpg"
          },
          {
            "character": "Common House Proprietor",
            "credit_id": "5de1e513dcb6a300136cd5a6",
            "order": 514,
            "adult": false,
            "gender": 1,
            "id": 1668468,
            "known_for_department": "Acting",
            "name": "Ida Darvish",
            "original_name": "Ida Darvish",
            "popularity": 2.288,
            "profile_path": "/u0IusSD8zHVfhW4Uz7YjismbskA.jpg"
          },
          {
            "character": "Heavy Infantry Mando",
            "credit_id": "5de215b00cd446001235fd15",
            "order": 516,
            "adult": false,
            "gender": 2,
            "id": 1105706,
            "known_for_department": "Acting",
            "name": "Tait Fletcher",
            "original_name": "Tait Fletcher",
            "popularity": 37.527,
            "profile_path": "/zAVsHT2GBLPaQ4RpTopnHvIrCbv.jpg"
          },
          {
            "character": "Villager",
            "credit_id": "5de215cfdcb6a300116cd292",
            "order": 517,
            "adult": false,
            "gender": 2,
            "id": 2471163,
            "known_for_department": "Acting",
            "name": "Ed Gage",
            "original_name": "Ed Gage",
            "popularity": 1.4,
            "profile_path": "/t4rkP1cOX2qQZev04Jh0zFM8Yic.jpg"
          },
          {
            "character": "Sorgan Farmer",
            "credit_id": "5df6f795d1a89300147b02fc",
            "order": 531,
            "adult": false,
            "gender": 1,
            "id": 2483364,
            "known_for_department": "Acting",
            "name": "Adelina Saldana",
            "original_name": "Adelina Saldana",
            "popularity": 0.6,
            "profile_path": "/gViQ5Xp48n6PG3rHrQZXoslQes6.jpg"
          },
          {
            "character": "Caben",
            "credit_id": "5e20cc36a6d931001815915c",
            "order": 545,
            "adult": false,
            "gender": 2,
            "id": 1822025,
            "known_for_department": "Acting",
            "name": "Asif Ali",
            "original_name": "Asif Ali",
            "popularity": 3.04,
            "profile_path": "/akQ83JhkZ1IW6kg3x85FQsijn1a.jpg"
          },
          {
            "character": "Cara Dune",
            "credit_id": "5fe96ff807a808003e8db3ef",
            "order": 609,
            "adult": false,
            "gender": 1,
            "id": 78452,
            "known_for_department": "Acting",
            "name": "Gina Carano",
            "original_name": "Gina Carano",
            "popularity": 19.947,
            "profile_path": "/kDcHntDmMEzftUQc0ASV7FM71Ar.jpg"
          }
        ]
      },
      {
        "air_date": "2019-12-06",
        "episode_number": 5,
        "id": 1987335,
        "name": "Chapter 5: The Gunslinger",
        "overview": "The Mandalorian helps a rookie bounty hunter who is in over his head.",
        "production_code": "",
        "runtime": 37,
        "season_number": 1,
        "show_id": 82856,
        "still_path": "/o6enRShRThpenWqtaC5lXNsEa8w.jpg",
        "vote_average": 7.3,
        "vote_count": 105,
        "crew": [
          {
            "job": "Director of Photography",
            "department": "Camera",
            "credit_id": "5cb87a0c0e0a266b90f14452",
            "adult": false,
            "gender": 2,
            "id": 1406766,
            "known_for_department": "Camera",
            "name": "Barry Idoine",
            "original_name": "Barry Idoine",
            "popularity": 5.796,
            "profile_path": "/k12a8mxmefY54hQTzb2i3xIiuQQ.jpg"
          },
          {
            "job": "Editor",
            "department": "Editing",
            "credit_id": "5dd6b9503faba00015f70a1d",
            "adult": false,
            "gender": 2,
            "id": 71279,
            "known_for_department": "Editing",
            "name": "Andrew S. Eisen",
            "original_name": "Andrew S. Eisen",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Editor",
            "department": "Editing",
            "credit_id": "5de1e21e0cd446001935c8c4",
            "adult": false,
            "gender": 1,
            "id": 52450,
            "known_for_department": "Editing",
            "name": "Dana E. Glauberman",
            "original_name": "Dana E. Glauberman",
            "popularity": 1.22,
            "profile_path": "/dlik9ug8g80f2PWacp2Qdu3gyfD.jpg"
          },
          {
            "job": "Writer",
            "department": "Writing",
            "credit_id": "5f4fe65ca6fdaa00399499d9",
            "adult": false,
            "gender": 2,
            "id": 71538,
            "known_for_department": "Production",
            "name": "Dave Filoni",
            "original_name": "Dave Filoni",
            "popularity": 4.359,
            "profile_path": "/dDTTrShpCnCacxB3LhpPffFIdB5.jpg"
          },
          {
            "job": "First Assistant Director",
            "department": "Directing",
            "credit_id": "5f9e62a5344a8e00349cb56e",
            "adult": false,
            "gender": 1,
            "id": 2838919,
            "known_for_department": "Directing",
            "name": "Kim Richards",
            "original_name": "Kim Richards",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Production Supervisor",
            "department": "Production",
            "credit_id": "5fd03b3a0ce1bc003ef02c33",
            "adult": false,
            "gender": 0,
            "id": 2152272,
            "known_for_department": "Production",
            "name": "Clint Spillers",
            "original_name": "Clint Spillers",
            "popularity": 0.999,
            "profile_path": null
          },
          {
            "job": "Additional Director of Photography",
            "department": "Camera",
            "credit_id": "5fd04a1ad7cd06003d7cb4cd",
            "adult": false,
            "gender": 0,
            "id": 2887235,
            "known_for_department": "Camera",
            "name": "Ryley Brown",
            "original_name": "Ryley Brown",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Set Decoration",
            "department": "Art",
            "credit_id": "5fd04b9ae9c0dc003c36eb4e",
            "adult": false,
            "gender": 1,
            "id": 1389126,
            "known_for_department": "Art",
            "name": "Amanda Moss Serino",
            "original_name": "Amanda Moss Serino",
            "popularity": 1.4,
            "profile_path": null
          },
          {
            "job": "Property Master",
            "department": "Art",
            "credit_id": "5fd6c5a0db952d003e7cb5b3",
            "adult": false,
            "gender": 0,
            "id": 1463356,
            "known_for_department": "Art",
            "name": "Josh Roth",
            "original_name": "Josh Roth",
            "popularity": 0.716,
            "profile_path": null
          },
          {
            "job": "Director",
            "department": "Directing",
            "credit_id": "600f834e813cb6004280eea3",
            "adult": false,
            "gender": 2,
            "id": 71538,
            "known_for_department": "Production",
            "name": "Dave Filoni",
            "original_name": "Dave Filoni",
            "popularity": 4.359,
            "profile_path": "/dDTTrShpCnCacxB3LhpPffFIdB5.jpg"
          },
          {
            "job": "Stunt Double",
            "department": "Crew",
            "credit_id": "615f70ae8e2ba6008bf03a2a",
            "adult": false,
            "gender": 1,
            "id": 96754,
            "known_for_department": "Crew",
            "name": "Lauren Mary Kim",
            "original_name": "Lauren Mary Kim",
            "popularity": 2.639,
            "profile_path": "/h3HyClGURD5QsNSWSFhDiLnx8pq.jpg"
          }
        ],
        "guest_stars": [
          {
            "character": "Toro Calican",
            "credit_id": "5debb309158c850018802d73",
            "order": 518,
            "adult": false,
            "gender": 2,
            "id": 1246802,
            "known_for_department": "Acting",
            "name": "Jake Cannavale",
            "original_name": "Jake Cannavale",
            "popularity": 5.624,
            "profile_path": "/vfOkpbh28XS7lSqUZrRV2yBJ7Rw.jpg"
          },
          {
            "character": "Riot Mar",
            "credit_id": "5df6f7e426dac10014538d32",
            "order": 532,
            "adult": false,
            "gender": 2,
            "id": 62787,
            "known_for_department": "Acting",
            "name": "Rio Hackford",
            "original_name": "Rio Hackford",
            "popularity": 5.826,
            "profile_path": "/lzRk0FsLIJU8pNHhAlF5jijcdJr.jpg"
          },
          {
            "character": "Tusken Raider Scout #1",
            "credit_id": "5df6f80465686e0013867b42",
            "order": 533,
            "adult": false,
            "gender": 2,
            "id": 1571661,
            "known_for_department": "Acting",
            "name": "Troy Kotsur",
            "original_name": "Troy Kotsur",
            "popularity": 4.348,
            "profile_path": "/24K3og12jGBGL9dqH5OYFdjF9wu.jpg"
          },
          {
            "character": "Spaceport Operator (voice)",
            "credit_id": "5df6f818a6d9310017dad20b",
            "order": 534,
            "adult": false,
            "gender": 2,
            "id": 571562,
            "known_for_department": "Acting",
            "name": "Steve Blum",
            "original_name": "Steve Blum",
            "popularity": 5.067,
            "profile_path": "/cpO0muunoigq1WHegeOEI1AIQAo.jpg"
          },
          {
            "character": "EV-9D9 (voice) (uncredited)",
            "credit_id": "5eee510bb344090031ba3d07",
            "order": 548,
            "adult": false,
            "gender": 2,
            "id": 2,
            "known_for_department": "Acting",
            "name": "Mark Hamill",
            "original_name": "Mark Hamill",
            "popularity": 25.265,
            "profile_path": "/2ZulC2Ccq1yv3pemusks6Zlfy2s.jpg"
          },
          {
            "character": "Peli Motto",
            "credit_id": "5debb2e86d000c00145488b1",
            "order": 562,
            "adult": false,
            "gender": 1,
            "id": 12110,
            "known_for_department": "Acting",
            "name": "Amy Sedaris",
            "original_name": "Amy Sedaris",
            "popularity": 24.811,
            "profile_path": "/AjVjRYI1PaC11i4FqGSK1TkwOmq.jpg"
          },
          {
            "character": "Fennec Shand",
            "credit_id": "5debb31a6d000c001454892e",
            "order": 592,
            "adult": false,
            "gender": 1,
            "id": 21702,
            "known_for_department": "Acting",
            "name": "Ming-Na Wen",
            "original_name": "Ming-Na Wen",
            "popularity": 22.319,
            "profile_path": "/eqCzFF83It56cUdjpskzvg8jgq.jpg"
          }
        ]
      },
      {
        "air_date": "2019-12-13",
        "episode_number": 6,
        "id": 1987336,
        "name": "Chapter 6: The Prisoner",
        "overview": "The Mandalorian joins a crew of mercenaries on a dangerous mission.",
        "production_code": "",
        "runtime": 45,
        "season_number": 1,
        "show_id": 82856,
        "still_path": "/7Z9Bc58uLnp8gIDGtdi0jNEqYZY.jpg",
        "vote_average": 8.0,
        "vote_count": 99,
        "crew": [
          {
            "job": "Editor",
            "department": "Editing",
            "credit_id": "5cb87a27c3a36872c98161fd",
            "adult": false,
            "gender": 2,
            "id": 1580025,
            "known_for_department": "Editing",
            "name": "Jeff Seibenick",
            "original_name": "Jeff Seibenick",
            "popularity": 0.98,
            "profile_path": null
          },
          {
            "job": "Director of Photography",
            "department": "Camera",
            "credit_id": "5cb87a0c0e0a266b90f14452",
            "adult": false,
            "gender": 2,
            "id": 1406766,
            "known_for_department": "Camera",
            "name": "Barry Idoine",
            "original_name": "Barry Idoine",
            "popularity": 5.796,
            "profile_path": "/k12a8mxmefY54hQTzb2i3xIiuQQ.jpg"
          },
          {
            "job": "Story",
            "department": "Writing",
            "credit_id": "5f4fe7a54a4bf60035a2c706",
            "adult": false,
            "gender": 2,
            "id": 109542,
            "known_for_department": "Writing",
            "name": "Christopher L. Yost",
            "original_name": "Christopher L. Yost",
            "popularity": 2.107,
            "profile_path": null
          },
          {
            "job": "Teleplay",
            "department": "Writing",
            "credit_id": "5f4fe67f4a4bf60032a309f7",
            "adult": false,
            "gender": 2,
            "id": 51866,
            "known_for_department": "Directing",
            "name": "Rick Famuyiwa",
            "original_name": "Rick Famuyiwa",
            "popularity": 2.597,
            "profile_path": "/zvpQOPiD5RLfjKBJyNgHYNocy7X.jpg"
          },
          {
            "job": "Teleplay",
            "department": "Writing",
            "credit_id": "5f4fe7944a4bf60035a2c6d6",
            "adult": false,
            "gender": 2,
            "id": 109542,
            "known_for_department": "Writing",
            "name": "Christopher L. Yost",
            "original_name": "Christopher L. Yost",
            "popularity": 2.107,
            "profile_path": null
          },
          {
            "job": "First Assistant Director",
            "department": "Directing",
            "credit_id": "5f9e62a5344a8e00349cb56e",
            "adult": false,
            "gender": 1,
            "id": 2838919,
            "known_for_department": "Directing",
            "name": "Kim Richards",
            "original_name": "Kim Richards",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Production Supervisor",
            "department": "Production",
            "credit_id": "5fd03b3a0ce1bc003ef02c33",
            "adult": false,
            "gender": 0,
            "id": 2152272,
            "known_for_department": "Production",
            "name": "Clint Spillers",
            "original_name": "Clint Spillers",
            "popularity": 0.999,
            "profile_path": null
          },
          {
            "job": "Additional Director of Photography",
            "department": "Camera",
            "credit_id": "5fd04a1ad7cd06003d7cb4cd",
            "adult": false,
            "gender": 0,
            "id": 2887235,
            "known_for_department": "Camera",
            "name": "Ryley Brown",
            "original_name": "Ryley Brown",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Set Decoration",
            "department": "Art",
            "credit_id": "5fd04b9ae9c0dc003c36eb4e",
            "adult": false,
            "gender": 1,
            "id": 1389126,
            "known_for_department": "Art",
            "name": "Amanda Moss Serino",
            "original_name": "Amanda Moss Serino",
            "popularity": 1.4,
            "profile_path": null
          },
          {
            "job": "Stunt Double",
            "department": "Crew",
            "credit_id": "5fd5120d5ed9620040e079d2",
            "adult": false,
            "gender": 2,
            "id": 2889435,
            "known_for_department": "Crew",
            "name": "Barry Lowin",
            "original_name": "Barry Lowin",
            "popularity": 2.549,
            "profile_path": "/o9mP6E3QKpEZgcidyH4ucT5jnmB.jpg"
          },
          {
            "job": "Property Master",
            "department": "Art",
            "credit_id": "5fd6c5a0db952d003e7cb5b3",
            "adult": false,
            "gender": 0,
            "id": 1463356,
            "known_for_department": "Art",
            "name": "Josh Roth",
            "original_name": "Josh Roth",
            "popularity": 0.716,
            "profile_path": null
          },
          {
            "job": "Director",
            "department": "Directing",
            "credit_id": "600f832cc433ea003f471ae4",
            "adult": false,
            "gender": 2,
            "id": 51866,
            "known_for_department": "Directing",
            "name": "Rick Famuyiwa",
            "original_name": "Rick Famuyiwa",
            "popularity": 2.597,
            "profile_path": "/zvpQOPiD5RLfjKBJyNgHYNocy7X.jpg"
          }
        ],
        "guest_stars": [
          {
            "character": "Qin",
            "credit_id": "5df43512d1a89300127584db",
            "order": 519,
            "adult": false,
            "gender": 2,
            "id": 1100144,
            "known_for_department": "Acting",
            "name": "Ismael Cruz Córdova",
            "original_name": "Ismael Cruz Córdova",
            "popularity": 9.409,
            "profile_path": "/gx59ZkpGgGLEH79ciDgyWpUG8nt.jpg"
          },
          {
            "character": "Xi'an",
            "credit_id": "5df4352b4a4bf6001754ed7e",
            "order": 520,
            "adult": false,
            "gender": 1,
            "id": 3300,
            "known_for_department": "Acting",
            "name": "Natalia Tena",
            "original_name": "Natalia Tena",
            "popularity": 15.079,
            "profile_path": "/vpjfd4ueiuOmBaSWPzC4KdWEhBt.jpg"
          },
          {
            "character": "Burg",
            "credit_id": "5df58dd3d1a8930019783d83",
            "order": 521,
            "adult": false,
            "gender": 2,
            "id": 6574,
            "known_for_department": "Acting",
            "name": "Clancy Brown",
            "original_name": "Clancy Brown",
            "popularity": 53.185,
            "profile_path": "/xjg0ZIxP0tFcEQCTeRgKxNtLdpe.jpg"
          },
          {
            "character": "Ranzar \"Ran\" Malk",
            "credit_id": "5df58de96eecee0014993e20",
            "order": 522,
            "adult": false,
            "gender": 2,
            "id": 534,
            "known_for_department": "Acting",
            "name": "Mark Boone Junior",
            "original_name": "Mark Boone Junior",
            "popularity": 9.725,
            "profile_path": "/rcncVr356hpfKX9qOrKL3SJlEO7.jpg"
          },
          {
            "character": "Davan",
            "credit_id": "5df6f88ad1a89300147b04e9",
            "order": 535,
            "adult": false,
            "gender": 2,
            "id": 34202,
            "known_for_department": "Acting",
            "name": "Matt Lanter",
            "original_name": "Matt Lanter",
            "popularity": 10.003,
            "profile_path": "/2ms8DR9n4wh9ZU6lIuqsE58LPT9.jpg"
          },
          {
            "character": "Jib Dodger",
            "credit_id": "5df6f8bf26dac10014538d78",
            "order": 536,
            "adult": false,
            "gender": 2,
            "id": 51866,
            "known_for_department": "Directing",
            "name": "Rick Famuyiwa",
            "original_name": "Rick Famuyiwa",
            "popularity": 2.597,
            "profile_path": "/zvpQOPiD5RLfjKBJyNgHYNocy7X.jpg"
          },
          {
            "character": "Sash Ketter",
            "credit_id": "5df6f8cd26dac10014538d89",
            "order": 537,
            "adult": false,
            "gender": 1,
            "id": 928830,
            "known_for_department": "Directing",
            "name": "Deborah Chow",
            "original_name": "Deborah Chow",
            "popularity": 6.92,
            "profile_path": "/7XiXU4d7JqPGbhiGCvaRQclISRT.jpg"
          },
          {
            "character": "Zero (Q9-0) (Performance Artist)",
            "credit_id": "5df9b9d8609750001531b180",
            "order": 538,
            "adult": false,
            "gender": 2,
            "id": 2456535,
            "known_for_department": "Acting",
            "name": "Chris Bartlett",
            "original_name": "Chris Bartlett",
            "popularity": 2.599,
            "profile_path": "/tSD5t3Iq0lPeMi13EYa9A3nPLNS.jpg"
          },
          {
            "character": "Zero (voice)",
            "credit_id": "5df58cb865686e001383990f",
            "order": 564,
            "adult": false,
            "gender": 2,
            "id": 98103,
            "known_for_department": "Acting",
            "name": "Richard Ayoade",
            "original_name": "Richard Ayoade",
            "popularity": 8.094,
            "profile_path": "/qHKoy9kP4bsv4G9EkvU4FMUmYkS.jpg"
          },
          {
            "character": "Trapper Wolf",
            "credit_id": "5df6f8b3a6d9310012dacbb9",
            "order": 567,
            "adult": false,
            "gender": 2,
            "id": 71538,
            "known_for_department": "Production",
            "name": "Dave Filoni",
            "original_name": "Dave Filoni",
            "popularity": 4.359,
            "profile_path": "/dDTTrShpCnCacxB3LhpPffFIdB5.jpg"
          },
          {
            "character": "Migs Mayfeld",
            "credit_id": "5df4354afac502001185d57b",
            "order": 593,
            "adult": false,
            "gender": 2,
            "id": 109708,
            "known_for_department": "Acting",
            "name": "Bill Burr",
            "original_name": "Bill Burr",
            "popularity": 13.245,
            "profile_path": "/g8VqrigObjAE3QP1Xei1qgO4kfx.jpg"
          },
          {
            "character": "Greef Karga",
            "credit_id": "5fe96fe4c9054f003d3bfaea",
            "order": 605,
            "adult": false,
            "gender": 2,
            "id": 1101,
            "known_for_department": "Acting",
            "name": "Carl Weathers",
            "original_name": "Carl Weathers",
            "popularity": 31.528,
            "profile_path": "/9Tot1ywxTQA3vFCcAjyK6h9Dao3.jpg"
          }
        ]
      },
      {
        "air_date": "2019-12-18",
        "episode_number": 7,
        "id": 1987337,
        "name": "Chapter 7: The Reckoning",
        "overview": "An old rival extends an invitation for The Mandalorian to make peace.",
        "production_code": "",
        "runtime": 42,
        "season_number": 1,
        "show_id": 82856,
        "still_path": "/m483Gihn8vAt0cW5RXe5YRtchIQ.jpg",
        "vote_average": 8.6,
        "vote_count": 96,
        "crew": [
          {
            "job": "Director of Photography",
            "department": "Camera",
            "credit_id": "5cb879fac3a3686b0b86531f",
            "adult": false,
            "gender": 2,
            "id": 67113,
            "known_for_department": "Camera",
            "name": "Greig Fraser",
            "original_name": "Greig Fraser",
            "popularity": 2.366,
            "profile_path": "/cwj0aValmr7TGQ2OOQk5CAy1PWf.jpg"
          },
          {
            "job": "Director of Photography",
            "department": "Camera",
            "credit_id": "5cb87a0c0e0a266b90f14452",
            "adult": false,
            "gender": 2,
            "id": 1406766,
            "known_for_department": "Camera",
            "name": "Barry Idoine",
            "original_name": "Barry Idoine",
            "popularity": 5.796,
            "profile_path": "/k12a8mxmefY54hQTzb2i3xIiuQQ.jpg"
          },
          {
            "job": "Editor",
            "department": "Editing",
            "credit_id": "5dd6b9503faba00015f70a1d",
            "adult": false,
            "gender": 2,
            "id": 71279,
            "known_for_department": "Editing",
            "name": "Andrew S. Eisen",
            "original_name": "Andrew S. Eisen",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Writer",
            "department": "Writing",
            "credit_id": "5f4fe593a6fdaa0036948536",
            "adult": false,
            "gender": 2,
            "id": 15277,
            "known_for_department": "Acting",
            "name": "Jon Favreau",
            "original_name": "Jon Favreau",
            "popularity": 25.467,
            "profile_path": "/8MtRRnEHaBSw8Ztdl8saXiw1egP.jpg"
          },
          {
            "job": "First Assistant Director",
            "department": "Directing",
            "credit_id": "5f9e62a5344a8e00349cb56e",
            "adult": false,
            "gender": 1,
            "id": 2838919,
            "known_for_department": "Directing",
            "name": "Kim Richards",
            "original_name": "Kim Richards",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Production Supervisor",
            "department": "Production",
            "credit_id": "5fd03b3a0ce1bc003ef02c33",
            "adult": false,
            "gender": 0,
            "id": 2152272,
            "known_for_department": "Production",
            "name": "Clint Spillers",
            "original_name": "Clint Spillers",
            "popularity": 0.999,
            "profile_path": null
          },
          {
            "job": "Additional Director of Photography",
            "department": "Camera",
            "credit_id": "5fd04a1ad7cd06003d7cb4cd",
            "adult": false,
            "gender": 0,
            "id": 2887235,
            "known_for_department": "Camera",
            "name": "Ryley Brown",
            "original_name": "Ryley Brown",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Set Decoration",
            "department": "Art",
            "credit_id": "5fd04b9ae9c0dc003c36eb4e",
            "adult": false,
            "gender": 1,
            "id": 1389126,
            "known_for_department": "Art",
            "name": "Amanda Moss Serino",
            "original_name": "Amanda Moss Serino",
            "popularity": 1.4,
            "profile_path": null
          },
          {
            "job": "Property Master",
            "department": "Art",
            "credit_id": "5fd6c5a0db952d003e7cb5b3",
            "adult": false,
            "gender": 0,
            "id": 1463356,
            "known_for_department": "Art",
            "name": "Josh Roth",
            "original_name": "Josh Roth",
            "popularity": 0.716,
            "profile_path": null
          },
          {
            "job": "Art Direction",
            "department": "Art",
            "credit_id": "5fd6c769681888004097d1ca",
            "adult": false,
            "gender": 0,
            "id": 1324829,
            "known_for_department": "Art",
            "name": "Michael Manson",
            "original_name": "Michael Manson",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Director",
            "department": "Directing",
            "credit_id": "600f83920816c700417d2dc5",
            "adult": false,
            "gender": 1,
            "id": 928830,
            "known_for_department": "Directing",
            "name": "Deborah Chow",
            "original_name": "Deborah Chow",
            "popularity": 6.92,
            "profile_path": "/7XiXU4d7JqPGbhiGCvaRQclISRT.jpg"
          }
        ],
        "guest_stars": [
          {
            "character": "The Client",
            "credit_id": "5de214d54f5801000f00770c",
            "order": 2,
            "adult": false,
            "gender": 2,
            "id": 6818,
            "known_for_department": "Directing",
            "name": "Werner Herzog",
            "original_name": "Werner Herzog",
            "popularity": 4.553,
            "profile_path": "/vokqteY91Pda0L13pTqTzTCo7vV.jpg"
          },
          {
            "character": "Kuiil (voice)",
            "credit_id": "5df6f4ac65686e00188611d3",
            "order": 539,
            "adult": false,
            "gender": 2,
            "id": 1733,
            "known_for_department": "Acting",
            "name": "Nick Nolte",
            "original_name": "Nick Nolte",
            "popularity": 18.97,
            "profile_path": "/jpYzFBi6zfn8CHVaXmqgiOTas4V.jpg"
          },
          {
            "character": "Zabrak Fighter",
            "credit_id": "5dfaf7a55ed9620016e40cca",
            "order": 540,
            "adult": false,
            "gender": 2,
            "id": 1602548,
            "known_for_department": "Acting",
            "name": "Dave Reaves",
            "original_name": "Dave Reaves",
            "popularity": 1.4,
            "profile_path": "/vh5HbJJYB0RdK3nptfybIx5EnRv.jpg"
          },
          {
            "character": "Bike Scout Trooper #2",
            "credit_id": "5dfaf77d26dac100125a1e81",
            "order": 542,
            "adult": false,
            "gender": 2,
            "id": 115974,
            "known_for_department": "Acting",
            "name": "Adam Pally",
            "original_name": "Adam Pally",
            "popularity": 8.553,
            "profile_path": "/yY13PEaVbPoXT5MkitVxTfdAZnU.jpg"
          },
          {
            "character": "IG-11 (Performance Artist)",
            "credit_id": "5dcef449e263bb001175bae2",
            "order": 546,
            "adult": false,
            "gender": 2,
            "id": 62787,
            "known_for_department": "Acting",
            "name": "Rio Hackford",
            "original_name": "Rio Hackford",
            "popularity": 5.826,
            "profile_path": "/lzRk0FsLIJU8pNHhAlF5jijcdJr.jpg"
          },
          {
            "character": "IG-11 (voice)",
            "credit_id": "5de214010cd446001235fa6e",
            "order": 547,
            "adult": false,
            "gender": 2,
            "id": 55934,
            "known_for_department": "Directing",
            "name": "Taika Waititi",
            "original_name": "Taika Waititi",
            "popularity": 27.104,
            "profile_path": "/aH6MgwFhomAPNBRPyO2fhpU5kbk.jpg"
          },
          {
            "character": "Kuiil (Performance Artist)",
            "credit_id": "5dcef41cb76cbb00137768bb",
            "order": 566,
            "adult": false,
            "gender": 1,
            "id": 95747,
            "known_for_department": "Acting",
            "name": "Misty Rosas",
            "original_name": "Misty Rosas",
            "popularity": 4.301,
            "profile_path": "/aCa0ukemG7x3wAxtR1BM5v0BvrL.jpg"
          },
          {
            "character": "Greef Karga",
            "credit_id": "5fe96fe4c9054f003d3bfaea",
            "order": 605,
            "adult": false,
            "gender": 2,
            "id": 1101,
            "known_for_department": "Acting",
            "name": "Carl Weathers",
            "original_name": "Carl Weathers",
            "popularity": 31.528,
            "profile_path": "/9Tot1ywxTQA3vFCcAjyK6h9Dao3.jpg"
          },
          {
            "character": "RA-7 Droid (Performance Artist)",
            "credit_id": "5dfaf86b5ed9620016e40e6b",
            "order": 608,
            "adult": false,
            "gender": 2,
            "id": 2456535,
            "known_for_department": "Acting",
            "name": "Chris Bartlett",
            "original_name": "Chris Bartlett",
            "popularity": 2.599,
            "profile_path": "/tSD5t3Iq0lPeMi13EYa9A3nPLNS.jpg"
          },
          {
            "character": "Cara Dune",
            "credit_id": "5fe96ff807a808003e8db3ef",
            "order": 609,
            "adult": false,
            "gender": 1,
            "id": 78452,
            "known_for_department": "Acting",
            "name": "Gina Carano",
            "original_name": "Gina Carano",
            "popularity": 19.947,
            "profile_path": "/kDcHntDmMEzftUQc0ASV7FM71Ar.jpg"
          },
          {
            "character": "Moff Gideon",
            "credit_id": "5fe97032df857c0041384627",
            "order": 610,
            "adult": false,
            "gender": 2,
            "id": 4808,
            "known_for_department": "Acting",
            "name": "Giancarlo Esposito",
            "original_name": "Giancarlo Esposito",
            "popularity": 34.64,
            "profile_path": "/lBvDQZjxhIGMbH61iHnqerpbqHc.jpg"
          }
        ]
      },
      {
        "air_date": "2019-12-27",
        "episode_number": 8,
        "id": 2023593,
        "name": "Chapter 8: Redemption",
        "overview": "The Mandalorian comes face-to-face with an unexpected enemy.",
        "production_code": "",
        "runtime": 50,
        "season_number": 1,
        "show_id": 82856,
        "still_path": "/v36aZwxTsPAvqsssLPVno3VFvg5.jpg",
        "vote_average": 8.6,
        "vote_count": 97,
        "crew": [
          {
            "job": "Editor",
            "department": "Editing",
            "credit_id": "5cb87a27c3a36872c98161fd",
            "adult": false,
            "gender": 2,
            "id": 1580025,
            "known_for_department": "Editing",
            "name": "Jeff Seibenick",
            "original_name": "Jeff Seibenick",
            "popularity": 0.98,
            "profile_path": null
          },
          {
            "job": "Director of Photography",
            "department": "Camera",
            "credit_id": "5cb87a0c0e0a266b90f14452",
            "adult": false,
            "gender": 2,
            "id": 1406766,
            "known_for_department": "Camera",
            "name": "Barry Idoine",
            "original_name": "Barry Idoine",
            "popularity": 5.796,
            "profile_path": "/k12a8mxmefY54hQTzb2i3xIiuQQ.jpg"
          },
          {
            "job": "Writer",
            "department": "Writing",
            "credit_id": "5f4fe593a6fdaa0036948536",
            "adult": false,
            "gender": 2,
            "id": 15277,
            "known_for_department": "Acting",
            "name": "Jon Favreau",
            "original_name": "Jon Favreau",
            "popularity": 25.467,
            "profile_path": "/8MtRRnEHaBSw8Ztdl8saXiw1egP.jpg"
          },
          {
            "job": "Production Supervisor",
            "department": "Production",
            "credit_id": "5fd03b3a0ce1bc003ef02c33",
            "adult": false,
            "gender": 0,
            "id": 2152272,
            "known_for_department": "Production",
            "name": "Clint Spillers",
            "original_name": "Clint Spillers",
            "popularity": 0.999,
            "profile_path": null
          },
          {
            "job": "Additional Director of Photography",
            "department": "Camera",
            "credit_id": "5fd04a1ad7cd06003d7cb4cd",
            "adult": false,
            "gender": 0,
            "id": 2887235,
            "known_for_department": "Camera",
            "name": "Ryley Brown",
            "original_name": "Ryley Brown",
            "popularity": 0.6,
            "profile_path": null
          },
          {
            "job": "Set Decoration",
            "department": "Art",
            "credit_id": "5fd04b9ae9c0dc003c36eb4e",
            "adult": false,
            "gender": 1,
            "id": 1389126,
            "known_for_department": "Art",
            "name": "Amanda Moss Serino",
            "original_name": "Amanda Moss Serino",
            "popularity": 1.4,
            "profile_path": null
          },
          {
            "job": "Property Master",
            "department": "Art",
            "credit_id": "5fd6c5a0db952d003e7cb5b3",
            "adult": false,
            "gender": 0,
            "id": 1463356,
            "known_for_department": "Art",
            "name": "Josh Roth",
            "original_name": "Josh Roth",
            "popularity": 0.716,
            "profile_path": null
          },
          {
            "job": "Director",
            "department": "Directing",
            "credit_id": "600f838ac433ea003f471b39",
            "adult": false,
            "gender": 2,
            "id": 55934,
            "known_for_department": "Directing",
            "name": "Taika Waititi",
            "original_name": "Taika Waititi",
            "popularity": 27.104,
            "profile_path": "/aH6MgwFhomAPNBRPyO2fhpU5kbk.jpg"
          },
          {
            "job": "Stunt Double",
            "department": "Crew",
            "credit_id": "615f70ae8e2ba6008bf03a2a",
            "adult": false,
            "gender": 1,
            "id": 96754,
            "known_for_department": "Crew",
            "name": "Lauren Mary Kim",
            "original_name": "Lauren Mary Kim",
            "popularity": 2.639,
            "profile_path": "/h3HyClGURD5QsNSWSFhDiLnx8pq.jpg"
          }
        ],
        "guest_stars": [
          {
            "character": "Bike Scout Trooper #1",
            "credit_id": "5e05fa3cd236e600169bdd1a",
            "order": 541,
            "adult": false,
            "gender": 2,
            "id": 58224,
            "known_for_department": "Acting",
            "name": "Jason Sudeikis",
            "original_name": "Jason Sudeikis",
            "popularity": 17.697,
            "profile_path": "/smNK3CLjZYC6wAcgHeMqf90qU0O.jpg"
          },
          {
            "character": "Bike Scout Trooper #2",
            "credit_id": "5dfaf77d26dac100125a1e81",
            "order": 542,
            "adult": false,
            "gender": 2,
            "id": 115974,
            "known_for_department": "Acting",
            "name": "Adam Pally",
            "original_name": "Adam Pally",
            "popularity": 8.553,
            "profile_path": "/yY13PEaVbPoXT5MkitVxTfdAZnU.jpg"
          },
          {
            "character": "Young Din Djarin",
            "credit_id": "5e05fa6ceda4b70014293b89",
            "order": 543,
            "adult": false,
            "gender": 2,
            "id": 2491651,
            "known_for_department": "Acting",
            "name": "Aidan Bertola",
            "original_name": "Aidan Bertola",
            "popularity": 1.532,
            "profile_path": "/xMXATWE4X3geHyVCE3vqTB6KcPz.jpg"
          },
          {
            "character": "Mandalorian Warrior",
            "credit_id": "5e05faca26dac100176f93c9",
            "order": 544,
            "adult": false,
            "gender": 2,
            "id": 946854,
            "known_for_department": "Acting",
            "name": "Brendan Wayne",
            "original_name": "Brendan Wayne",
            "popularity": 10.228,
            "profile_path": "/5HWS16VfLyx3wKniej5mjzXbh1G.jpg"
          },
          {
            "character": "IG-11 (Performance Artist)",
            "credit_id": "5dcef449e263bb001175bae2",
            "order": 546,
            "adult": false,
            "gender": 2,
            "id": 62787,
            "known_for_department": "Acting",
            "name": "Rio Hackford",
            "original_name": "Rio Hackford",
            "popularity": 5.826,
            "profile_path": "/lzRk0FsLIJU8pNHhAlF5jijcdJr.jpg"
          },
          {
            "character": "IG-11 (voice)",
            "credit_id": "5de214010cd446001235fa6e",
            "order": 547,
            "adult": false,
            "gender": 2,
            "id": 55934,
            "known_for_department": "Directing",
            "name": "Taika Waititi",
            "original_name": "Taika Waititi",
            "popularity": 27.104,
            "profile_path": "/aH6MgwFhomAPNBRPyO2fhpU5kbk.jpg"
          },
          {
            "character": "Armorer",
            "credit_id": "5dcef473e263bb001175bb44",
            "order": 560,
            "adult": false,
            "gender": 1,
            "id": 1256020,
            "known_for_department": "Acting",
            "name": "Emily Swallow",
            "original_name": "Emily Swallow",
            "popularity": 24.183,
            "profile_path": "/jlgPZqdMsQaVv30oMqc40LzHYIw.jpg"
          },
          {
            "character": "Din Djarin Father",
            "credit_id": "5e05fab0eda4b7001228f845",
            "order": 563,
            "adult": false,
            "gender": 2,
            "id": 1567857,
            "known_for_department": "Acting",
            "name": "Bernard Bullen",
            "original_name": "Bernard Bullen",
            "popularity": 1.4,
            "profile_path": "/dmUerfyPtPoLZ7F363ShB7fbavD.jpg"
          },
          {
            "character": "Din Djarin Mother",
            "credit_id": "5df6f5e9a6d9310017dace60",
            "order": 602,
            "adult": false,
            "gender": 1,
            "id": 2477245,
            "known_for_department": "Acting",
            "name": "Alexandra Manea",
            "original_name": "Alexandra Manea",
            "popularity": 3.436,
            "profile_path": "/zQm8nQtS7E8eZeQLeDQNjObPQEL.jpg"
          },
          {
            "character": "Greef Karga",
            "credit_id": "5fe96fe4c9054f003d3bfaea",
            "order": 605,
            "adult": false,
            "gender": 2,
            "id": 1101,
            "known_for_department": "Acting",
            "name": "Carl Weathers",
            "original_name": "Carl Weathers",
            "popularity": 31.528,
            "profile_path": "/9Tot1ywxTQA3vFCcAjyK6h9Dao3.jpg"
          },
          {
            "character": "Cara Dune",
            "credit_id": "5fe96ff807a808003e8db3ef",
            "order": 609,
            "adult": false,
            "gender": 1,
            "id": 78452,
            "known_for_department": "Acting",
            "name": "Gina Carano",
            "original_name": "Gina Carano",
            "popularity": 19.947,
            "profile_path": "/kDcHntDmMEzftUQc0ASV7FM71Ar.jpg"
          },
          {
            "character": "Moff Gideon",
            "credit_id": "5fe97032df857c0041384627",
            "order": 610,
            "adult": false,
            "gender": 2,
            "id": 4808,
            "known_for_department": "Acting",
            "name": "Giancarlo Esposito",
            "original_name": "Giancarlo Esposito",
            "popularity": 34.64,
            "profile_path": "/lBvDQZjxhIGMbH61iHnqerpbqHc.jpg"
          }
        ]
      }
    ],
    "name": "Season 1",
    "overview": "Set after the fall of the Empire and before the emergence of the First Order. We follow the travails of a lone gunfighter in the outer reaches of the galaxy far from the authority of the New Republic.",
    "id": 110346,
    "poster_path": "/gcgkZIPu4drO5NCk4PIck0Z1hQk.jpg",
    "season_number": 1
  }