export default {
    "air_date": "2019-11-12",
    "episode_number": 1,
    "id": 1586260,
    "name": "Chapter 1: The Mandalorian",
    "overview": "A Mandalorian bounty hunter tracks a target for a well-paying client.",
    "production_code": "161176",
    "runtime": 41,
    "season_number": 1,
    "show_id": 82856,
    "still_path": "/lr8OEa0GzjZ0qmD9NuuMj6TRWxF.jpg",
    "vote_average": 7.8,
    "vote_count": 154,
    "crew": [
      {
        "job": "Editor",
        "department": "Editing",
        "credit_id": "5cb87a27c3a36872c98161fd",
        "adult": false,
        "gender": 2,
        "id": 1580025,
        "known_for_department": "Editing",
        "name": "Jeff Seibenick",
        "original_name": "Jeff Seibenick",
        "popularity": 0.98,
        "profile_path": null
      },
      {
        "job": "Director of Photography",
        "department": "Camera",
        "credit_id": "5cb879fac3a3686b0b86531f",
        "adult": false,
        "gender": 2,
        "id": 67113,
        "known_for_department": "Camera",
        "name": "Greig Fraser",
        "original_name": "Greig Fraser",
        "popularity": 2.366,
        "profile_path": "/cwj0aValmr7TGQ2OOQk5CAy1PWf.jpg"
      },
      {
        "job": "Writer",
        "department": "Writing",
        "credit_id": "5f4fe593a6fdaa0036948536",
        "adult": false,
        "gender": 2,
        "id": 15277,
        "known_for_department": "Acting",
        "name": "Jon Favreau",
        "original_name": "Jon Favreau",
        "popularity": 25.467,
        "profile_path": "/8MtRRnEHaBSw8Ztdl8saXiw1egP.jpg"
      },
      {
        "job": "First Assistant Director",
        "department": "Directing",
        "credit_id": "5f9e62a5344a8e00349cb56e",
        "adult": false,
        "gender": 1,
        "id": 2838919,
        "known_for_department": "Directing",
        "name": "Kim Richards",
        "original_name": "Kim Richards",
        "popularity": 0.6,
        "profile_path": null
      },
      {
        "job": "Production Supervisor",
        "department": "Production",
        "credit_id": "5fd03b3a0ce1bc003ef02c33",
        "adult": false,
        "gender": 0,
        "id": 2152272,
        "known_for_department": "Production",
        "name": "Clint Spillers",
        "original_name": "Clint Spillers",
        "popularity": 0.999,
        "profile_path": null
      },
      {
        "job": "Additional Director of Photography",
        "department": "Camera",
        "credit_id": "5fd047f5d18fb90040f7d077",
        "adult": false,
        "gender": 2,
        "id": 1406766,
        "known_for_department": "Camera",
        "name": "Barry Idoine",
        "original_name": "Barry Idoine",
        "popularity": 5.796,
        "profile_path": "/k12a8mxmefY54hQTzb2i3xIiuQQ.jpg"
      },
      {
        "job": "Set Decoration",
        "department": "Art",
        "credit_id": "5fd04b9ae9c0dc003c36eb4e",
        "adult": false,
        "gender": 1,
        "id": 1389126,
        "known_for_department": "Art",
        "name": "Amanda Moss Serino",
        "original_name": "Amanda Moss Serino",
        "popularity": 1.4,
        "profile_path": null
      },
      {
        "job": "Property Master",
        "department": "Art",
        "credit_id": "5fd6c5a0db952d003e7cb5b3",
        "adult": false,
        "gender": 0,
        "id": 1463356,
        "known_for_department": "Art",
        "name": "Josh Roth",
        "original_name": "Josh Roth",
        "popularity": 0.716,
        "profile_path": null
      },
      {
        "job": "Art Direction",
        "department": "Art",
        "credit_id": "5fd6c769681888004097d1ca",
        "adult": false,
        "gender": 0,
        "id": 1324829,
        "known_for_department": "Art",
        "name": "Michael Manson",
        "original_name": "Michael Manson",
        "popularity": 0.6,
        "profile_path": null
      },
      {
        "job": "Director",
        "department": "Directing",
        "credit_id": "600f834e813cb6004280eea3",
        "adult": false,
        "gender": 2,
        "id": 71538,
        "known_for_department": "Production",
        "name": "Dave Filoni",
        "original_name": "Dave Filoni",
        "popularity": 4.359,
        "profile_path": "/dDTTrShpCnCacxB3LhpPffFIdB5.jpg"
      }
    ],
    "guest_stars": [
      {
        "character": "The Client",
        "credit_id": "5de214d54f5801000f00770c",
        "order": 2,
        "adult": false,
        "gender": 2,
        "id": 6818,
        "known_for_department": "Directing",
        "name": "Werner Herzog",
        "original_name": "Werner Herzog",
        "popularity": 4.553,
        "profile_path": "/vokqteY91Pda0L13pTqTzTCo7vV.jpg"
      },
      {
        "character": "Bartender",
        "credit_id": "5dcb3476a06efe0014df6be0",
        "order": 500,
        "adult": false,
        "gender": 2,
        "id": 38571,
        "known_for_department": "Acting",
        "name": "John Beasley",
        "original_name": "John Beasley",
        "popularity": 6.943,
        "profile_path": "/tpZQojv2UfelPHr1eSphcp0iEpJ.jpg"
      },
      {
        "character": "Alpha Trawler",
        "credit_id": "5dcb34aecc277c0014dec9c8",
        "order": 501,
        "adult": false,
        "gender": 2,
        "id": 1105706,
        "known_for_department": "Acting",
        "name": "Tait Fletcher",
        "original_name": "Tait Fletcher",
        "popularity": 37.527,
        "profile_path": "/zAVsHT2GBLPaQ4RpTopnHvIrCbv.jpg"
      },
      {
        "character": "Quarren Trawler",
        "credit_id": "5dcb34ef79a1c30013430eeb",
        "order": 502,
        "adult": false,
        "gender": 2,
        "id": 1686301,
        "known_for_department": "Acting",
        "name": "Dmitrious Bistrevsky",
        "original_name": "Dmitrious Bistrevsky",
        "popularity": 1.556,
        "profile_path": "/lxh4R3KDeg2bdV6WZWQr8maTXh0.jpg"
      },
      {
        "character": "Ferryman",
        "credit_id": "5dcb351779a1c30013430f40",
        "order": 503,
        "adult": false,
        "gender": 2,
        "id": 2456535,
        "known_for_department": "Acting",
        "name": "Chris Bartlett",
        "original_name": "Chris Bartlett",
        "popularity": 2.599,
        "profile_path": "/tSD5t3Iq0lPeMi13EYa9A3nPLNS.jpg"
      },
      {
        "character": "Speeder Pilot",
        "credit_id": "5dcb352fa06efe0017df455e",
        "order": 504,
        "adult": false,
        "gender": 2,
        "id": 20405,
        "known_for_department": "Acting",
        "name": "Brian Posehn",
        "original_name": "Brian Posehn",
        "popularity": 10.467,
        "profile_path": "/kg93LNpDQaRoosR4gVt7SsA3oL1.jpg"
      },
      {
        "character": "Beta Trawler",
        "credit_id": "5dcb36b4cc277c0014dece8e",
        "order": 505,
        "adult": false,
        "gender": 2,
        "id": 2456540,
        "known_for_department": "Crew",
        "name": "Ryan Watson",
        "original_name": "Ryan Watson",
        "popularity": 1.114,
        "profile_path": "/3Ld7rcvDDtkCpnKw5MSprwrbPio.jpg"
      },
      {
        "character": "Bounty Hunter Gekko",
        "credit_id": "5df6f60ba6d9310012dac8eb",
        "order": 529,
        "adult": false,
        "gender": 2,
        "id": 1215981,
        "known_for_department": "Acting",
        "name": "Dominic Pace",
        "original_name": "Dominic Pace",
        "popularity": 4.017,
        "profile_path": "/9req1Q8f8cR1dKCcLBYzNHQ1cx9.jpg"
      },
      {
        "character": "Kuiil (voice)",
        "credit_id": "5df6f4ac65686e00188611d3",
        "order": 539,
        "adult": false,
        "gender": 2,
        "id": 1733,
        "known_for_department": "Acting",
        "name": "Nick Nolte",
        "original_name": "Nick Nolte",
        "popularity": 18.97,
        "profile_path": "/jpYzFBi6zfn8CHVaXmqgiOTas4V.jpg"
      },
      {
        "character": "IG-11 (Performance Artist)",
        "credit_id": "5dcef449e263bb001175bae2",
        "order": 546,
        "adult": false,
        "gender": 2,
        "id": 62787,
        "known_for_department": "Acting",
        "name": "Rio Hackford",
        "original_name": "Rio Hackford",
        "popularity": 5.826,
        "profile_path": "/lzRk0FsLIJU8pNHhAlF5jijcdJr.jpg"
      },
      {
        "character": "IG-11 (voice)",
        "credit_id": "5de214010cd446001235fa6e",
        "order": 547,
        "adult": false,
        "gender": 2,
        "id": 55934,
        "known_for_department": "Directing",
        "name": "Taika Waititi",
        "original_name": "Taika Waititi",
        "popularity": 27.104,
        "profile_path": "/aH6MgwFhomAPNBRPyO2fhpU5kbk.jpg"
      },
      {
        "character": "Armorer",
        "credit_id": "5dcef473e263bb001175bb44",
        "order": 560,
        "adult": false,
        "gender": 1,
        "id": 1256020,
        "known_for_department": "Acting",
        "name": "Emily Swallow",
        "original_name": "Emily Swallow",
        "popularity": 24.183,
        "profile_path": "/jlgPZqdMsQaVv30oMqc40LzHYIw.jpg"
      },
      {
        "character": "Din Djarin Father",
        "credit_id": "5e05fab0eda4b7001228f845",
        "order": 563,
        "adult": false,
        "gender": 2,
        "id": 1567857,
        "known_for_department": "Acting",
        "name": "Bernard Bullen",
        "original_name": "Bernard Bullen",
        "popularity": 1.4,
        "profile_path": "/dmUerfyPtPoLZ7F363ShB7fbavD.jpg"
      },
      {
        "character": "Kuiil (Performance Artist)",
        "credit_id": "5dcef41cb76cbb00137768bb",
        "order": 566,
        "adult": false,
        "gender": 1,
        "id": 95747,
        "known_for_department": "Acting",
        "name": "Misty Rosas",
        "original_name": "Misty Rosas",
        "popularity": 4.301,
        "profile_path": "/aCa0ukemG7x3wAxtR1BM5v0BvrL.jpg"
      },
      {
        "character": "Mythrol",
        "credit_id": "5dcb349079a1c30013430e54",
        "order": 575,
        "adult": false,
        "gender": 2,
        "id": 52117,
        "known_for_department": "Acting",
        "name": "Horatio Sanz",
        "original_name": "Horatio Sanz",
        "popularity": 4.33,
        "profile_path": "/ckz64bpwFOhF1tMu1klDk5AT9Ck.jpg"
      },
      {
        "character": "Din Djarin Mother",
        "credit_id": "5df6f5e9a6d9310017dace60",
        "order": 602,
        "adult": false,
        "gender": 1,
        "id": 2477245,
        "known_for_department": "Acting",
        "name": "Alexandra Manea",
        "original_name": "Alexandra Manea",
        "popularity": 3.436,
        "profile_path": "/zQm8nQtS7E8eZeQLeDQNjObPQEL.jpg"
      },
      {
        "character": "Greef Karga",
        "credit_id": "5fe96fe4c9054f003d3bfaea",
        "order": 605,
        "adult": false,
        "gender": 2,
        "id": 1101,
        "known_for_department": "Acting",
        "name": "Carl Weathers",
        "original_name": "Carl Weathers",
        "popularity": 31.528,
        "profile_path": "/9Tot1ywxTQA3vFCcAjyK6h9Dao3.jpg"
      },
      {
        "character": "Young Mandalorian (uncredited)",
        "credit_id": "60ec9f6bc2b9df00290ad2a0",
        "order": 612,
        "adult": false,
        "gender": 2,
        "id": 2491651,
        "known_for_department": "Acting",
        "name": "Aidan Bertola",
        "original_name": "Aidan Bertola",
        "popularity": 1.532,
        "profile_path": "/xMXATWE4X3geHyVCE3vqTB6KcPz.jpg"
      },
      {
        "character": "Dr. Penn Pershing",
        "credit_id": "64118697323eba00c5ec3c90",
        "order": 624,
        "adult": false,
        "gender": 2,
        "id": 167862,
        "known_for_department": "Acting",
        "name": "Omid Abtahi",
        "original_name": "Omid Abtahi",
        "popularity": 6.347,
        "profile_path": "/gyXa16wW4vSUFmH014JGojstDeN.jpg"
      }
    ]
  }